name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: translatorregistry2026.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t translatorregistry2026.azurecr.io/translator-frontend:v1 .
          
      - name: Push to ACR
        run: |
          docker push translatorregistry2026.azurecr.io/translator-frontend:v1